project:
  type: website
  render:
    - index.qmd
    - "/tutoriels/**/*.qmd"

website:
  title: "Formations R dispensées au MASA"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - icon: github
        href: https://github.com/SSM-Agriculture/site-tutoriels
    background: "#c0a4eb"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
   - include-code-files

